spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: serviceA
          uri: lb://serviceA
          predicates:
            - Path=/serviceA/**
          filters:
            #- PrefixPath=/brand
            - StripPrefix=1
        - id: serviceB
          uri: lb://serviceB
          predicates:
            - Path=/serviceB/**
          filters:
            #- PrefixPath=/brand
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            #- PrefixPath=/brand
            - StripPrefix=1
  application:
    name: gateway-web
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true