server:
  port: 8080
spring:
  application:
    name: multi

  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/db?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/db?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        wall:
          comment-allow: true
          none-base-statement-allow: true
          variant-check: false
          multi-statement-allow: true
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
      lazy: true # 懒加载数据源

